name: Verify Changelog
on:
  pull_request:
    types: [edited, labeled, opened, ready_for_review, reopened, review_requested, synchronize, unlabeled]

jobs:
  verify-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: dangoslen/changelog-enforcer@8b5e9dc3121363bb7c0115f8533404d92af382de # v3.7.0
        with:
          skipLabels: 'dependabot, skip-changelog'
